---
title: "Day 6 Notes: Standard Deviation"
output:
  html_document:
    css: ./style.css
    toc: yes
    toc_float: yes
    theme: cosmo
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: console
---
  
```{r global_options, include = FALSE}
library(knitr)
library(tidyverse)
knitr::opts_chunk$set(eval = TRUE, results = TRUE)
```

---
  
## Today's Agenda
- Recap
- Variance
- Sample vs Population
- Standard Deviation

---

## Recap

    
## Variance
    
$$\text{variance} = \sigma^2 = \displaystyle \frac{\sum_{i=1}^n (\mu-x_i)^2}{N}$$

```{r}
# create toy data to experiment with
toy_data <- c(6, 5, 6, 10, 9, 8, 6)
toy_data
```


## Population vs. Sample


### Variance in a sample

$$\text{variance} = s^2 = \displaystyle \frac{\sum_{i=1}^n (\bar{x}-x_i)^2}{n-1}$$

## Variance in a population

$$\text{variance} = \sigma^2 = \displaystyle \frac{\sum_{i=1}^n (\mu-x_i)^2}{N}$$



## Standard Deviation



$$\text{standard deviation} = \sqrt{\text{variance}} = \sqrt{\sigma^2} = \sigma = \sqrt{\displaystyle \frac{\sum_{i=1}^n (\mu-x_i)^2}{N}}$$

### standard deviation in a Sample

$$\text{standard deviation} = \sqrt{\text{variance}} = \sqrt{s^2} = s = \sqrt{\displaystyle \frac{\sum_{i=1}^n (\bar{x}-x_i)^2}{n-1}}$$



### 68-95-99



